services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time-tracker-backend
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: time-tracker-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: degusta-box
      MYSQL_USER: degustabox
      MYSQL_PASSWORD: degustabox
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: time-tracker-nginx
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./etc/docker/nginx-default.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data: