controllers:
    resource:
        path: ../src/App/Controller/
        namespace: DegustaBox\App\Controller
    type: attribute
    prefix: /api/app/

core:
    resource: '@CoreBundle/Resources/config/routes.yaml'
    prefix: /api/core/

auth:
    resource: '@AuthBundle/Resources/config/routes.yaml'
    prefix: /api/auth/